---
title: Configuracao Sistema
---
classDiagram
direction TB
	namespace WindowsFormsApplication2_Configurar_Sistema {
        class IConfiguracaoSistema {
	        +PropertyChanged ~~ PropertyChangedEventHandler
	        -currentControl : UserControl
	        -initialState : Dictionary~string, object~
	        -hasUnsavedChanges : bool
	        +PRCO01 : decimal
	        +PRCO02 : decimal
	        +PRCO03 : decimal
	        +PRCO04 : string
	        +PRCO05 : int
	        +PRCO06 : int
	        +PRCO07 : int
	        +PRCO08 : bool
	        +PRCO09 : bool
	        +PRCO10 : bool
	        +PRRB01 : bool
	        +PRRB02 : bool
	        +LIRB01 : bool
	        +LIRB02 : bool
	        +LIRB03 : bool
	        +LIRB04 : bool
	        +LIRB05 : bool
	        +LICO01 : bool
	        +LICO02 : bool
	        +LICO03 : bool
	        +LICO04 : bool
	        +LICO05 : bool
	        +LICO06 : bool
	        +LICO07 : bool
	        +LICO08 : bool
	        +LICO09 : bool
	        +LICO10 : int
	        +LICO11_Futura : int
	        +LICO11_Passada : int
	        +LICO12 : int
	        +LICO13 : string
	        +LICO14 : string
	        +LICO15 : bool
	        +LIEE01 : bool
	        +LIEE02 : string
	        +LIEE03 : bool
	        +LIEE04 : bool
	        +LIEE05 : string
	        +LIEE06 : string
	        +LIEE07 : string
	        +FFIN01 : bool
	        +FFIS01 : bool
	        +FFIS02 : bool
	        +FFIS03 : bool
	        +FFIS04 : bool
	        +FFIS05 : bool
	        +FFIS06 : bool
	        +FFIS07 : bool
	        +FBOL01 : bool
	        +FBOL02 : bool
	        +FBOL03 : bool
	        +FBOL04 : bool
	        +FBOL05 : bool
	        +COCL01 : bool
	        +COCL02 : bool
	        +COCB01 : bool
	        +COCB02 : bool
	        +COCB03 : bool
	        +COCB04 : bool
	        +COCB05 : bool
	        +COCB06 : bool
	        +COCB07 : bool
	        +COCB08 : bool
	        +COCB09 : bool
	        +COCB10 : bool
	        +COCO01 : bool
	        +COCO02 : bool
	        +COCO03 : bool
	        +COCO04 : bool
	        +COCO05 : bool
	        +COCO06 : bool
	        +COCO07 : bool
	        +COCO08 : bool
	        +COCO09 : bool
	        +COCO10 : bool
	        +COCO11N : bool
	        +COCO12N : bool
	        +COCO11 : string
	        +COCO13 : string
	        +COCO17 : DateTime
	        +BACG01 : string
	        +BACG02 : string
	        +BACG03 : string
	        +BACG04 : string
	        +BACG05 : string
	        +BACG06 : int
	        +BACG07 : string
	        +BACG08 : string
	        +BACG09 : string
	        +BACG10 : string
	        +BACO01 : int
	        +BACO02 : bool
	        +BACO03 : bool
	        +BACO04 : bool
	        +BACO05 : bool
	        +BACO06 : bool
	        +BACO07 : bool
	        +BACO08 : bool
	        +BACO09 : bool
	        +BACO10 : bool
	        +BACO11 : bool
	        +BACO12 : bool
	        +BAIM01 : bool
	        +BAIM02 : bool
	        +BAIM03 : bool
	        +BAIM04 : bool
	        +BAIM05 : bool
	        +BAIM06 : bool
	        +BAIM07 : bool
	        +BAIM08 : bool
	        +BAIM09 : bool
	        +BAIM10 : bool
	        #OnPropertyChanged(string) void
	        +IConfiguracaoSistema()
	        +Salvar() void
	        +Salvar_Producao(SqlConnection, SqlTransaction) void
	        +Salvar_Logistica(SqlConnection, SqlTransaction) void
	        +Salvar_Comercial(SqlConnection, SqlTransaction) void
	        +Salvar_Comercial1(SqlConnection, SqlTransaction) void
	        +Salvar_Bar(SqlConnection, SqlTransaction) void
	        +Buscar_Configuracao_Producao() void
	        +Buscar_Configuracao_Logistica() void
	        +Buscar_Configuracao_Comercial() void
	        +Buscar_Configuracao_Comercial1() void
	        +Buscar_Configuracao_Bar() void
        }
        class BarSistema {
	        -configuracao : IConfiguracaoSistema
	        ~~ cmbBACG01_SelectedIndexChanged
	        ~~ cmbBACG02_SelectedIndexChanged
	        ~~ cmbBACG03_SelectedIndexChanged
	        ~~ cmbBACG04_SelectedIndexChanged
	        ~~ cmbBACG05_SelectedIndexChanged
	        ~~ txtBACG06_TextChanged
	        ~~ cmbBACG07_SelectedIndexChanged
	        ~~ cmbBACG08_SelectedIndexChanged
	        ~~ cmbBACG09_SelectedIndexChanged
	        ~~ txtBACG10_TextChanged
	        ~~ chkBACO01_CheckedChanged
	        ~~ chkBACO02_CheckedChanged
	        ~~ chkBACO03_CheckedChanged
	        ~~ chkBACO04_CheckedChanged
	        ~~ chkBACO05_CheckedChanged
	        ~~ chkBACO06_CheckedChanged
	        ~~ chkBACO07_CheckedChanged
	        ~~ chkBACO08_CheckedChanged
	        ~~ chkBACO09_CheckedChanged
	        ~~ chkBACO10_CheckedChanged
	        ~~ chkBACO11_CheckedChanged
	        ~~ chkBACO12_CheckedChanged
	        ~~ chkBAIM01_CheckedChanged
	        ~~ chkBAIM02_CheckedChanged
	        ~~ chkBAIM03_CheckedChanged
	        ~~ chkBAIM04_CheckedChanged
	        ~~ chkBAIM05_CheckedChanged
	        ~~ chkBAIM06_CheckedChanged
	        ~~ chkBAIM07_CheckedChanged
	        ~~ chkBAIM08_CheckedChanged
	        ~~ chkBAIM09_CheckedChanged
	        ~~ chkBAIM10_CheckedChanged
	        +BarSistema(IConfiguracaoSistema)
	        +Lista_Empresas() void
	        +Buscar_CFOP() void
	        -Chk_CheckedChanged(object, EventArgs) void
	        +DesmarcarTodos() void
	        +Atualizar() void
	        -panelImpressao_Paint(object, PaintEventArgs) void
	        -lblBACO11_Click(object, EventArgs) void
        }
        class ComercialSistema {
	        -configuracao : IConfiguracaoSistema
	        ~~ chkFFIN01_CheckedChanged
	        ~~ chkFFIS01_CheckedChanged
	        ~~ chkFFIS02_CheckedChanged
	        ~~ chkFFIS03_CheckedChanged
	        ~~ chkFFIS04_CheckedChanged
	        ~~ chkFFIS05_CheckedChanged
	        ~~ chkFFIS06_CheckedChanged
	        ~~ checkFFIS07_CheckedChanged
	        ~~ chkFBOL01_CheckedChanged
	        ~~ chkFBOL02_CheckedChanged
	        ~~ chkFBOL03_CheckedChanged
	        ~~ chkFBOL04_CheckedChanged
	        ~~ chkFBOL05_CheckedChanged
	        +ComercialSistema(IConfiguracaoSistema)
	        -Chk_CheckedChanged(object, EventArgs) void
	        +DesmarcarTodos() void
	        +Atualizar() void
	        -panel5_Paint(object, PaintEventArgs) void
	        -label4_Click(object, EventArgs) void
	        -label6_Click(object, EventArgs) void
	        -panel6_Paint(object, PaintEventArgs) void
	        -panelFiscal_Paint(object, PaintEventArgs) void
	        -chkFFIS01_CheckedChanged(object, EventArgs) void
	        -chkFFIS05_CheckedChanged(object, EventArgs) void
	        -checkFFIS07_CheckedChanged(object, EventArgs) void
	        -CreateSpecialConfigurationsPanel() void
        }
        class ComercialSistema1 {
	        -configuracao : IConfiguracaoSistema
	        ~~ chkCOCL01_CheckedChanged
	        ~~ chkCOCL02_CheckedChanged
	        ~~ chkCOCB01_CheckedChanged
	        ~~ chkCOCB02_CheckedChanged
	        ~~ chkCOCB03_CheckedChanged
	        ~~ chkCOCB04_CheckedChanged
	        ~~ chkCOCB05_CheckedChanged
	        ~~ chkCOCB06_CheckedChanged
	        ~~ chkCOCB07_CheckedChanged
	        ~~ chkCOCB08_CheckedChanged
	        ~~ chkCOCB09_CheckedChanged
	        ~~ chkCOCB10_CheckedChanged
	        ~~ chkCOCO01_CheckedChanged
	        ~~ chkCOCO02_CheckedChanged
	        ~~ chkCOCO03_CheckedChanged
	        ~~ chkCOCO04_CheckedChanged
	        ~~ chkCOCO05_CheckedChanged
	        ~~ chkCOCO06_CheckedChanged
	        ~~ chkCOCO07_CheckedChanged
	        ~~ chkCOCO08_CheckedChanged
	        ~~ chkCOCO09_CheckedChanged
	        ~~ chkCOCO10_CheckedChanged
	        ~~ chkCOCO11_CheckedChanged
	        ~~ chkCOCO12_CheckedChanged
	        ~~ txtCOCO12_TextChanged
	        ~~ dtCOCO17_ValueChanged
	        ~~ btnConfigurar_Click
	        ~~ btnCOCO14_Click
	        ~~ btnConfigurarPedidooClausula_Click
	        +ComercialSistema1(IConfiguracaoSistema)
	        -Chk_CheckedChanged(object, EventArgs) void
	        -Txt_TextChanged(object, EventArgs) void
	        -DtCOCO17_ValueChanged(object, EventArgs) void
	        -BtnConfigurar_Click(object, EventArgs) void
	        -BtnBuscarImagem_Click(object, EventArgs) void
	        -CarregarLogo() void
	        -ImageToByteArray(Image) byte[]
	        +DesmarcarTodos() void
	        +Atualizar() void
	        -CreateSpecialConfigurationsPanel() void
	        -panelRestricoes_Paint(object, PaintEventArgs) void
        }
        class ProducaoSistema {
	        -configuracao : IConfiguracaoSistema
	        ~~ txtPRCO01_TextChanged
	        ~~ txtPRCO02_Leave
	        ~~ txtPRCO03_TextChanged
	        ~~ cmbPRCO04_SelectedIndexChanged
	        ~~ txtPRCO05_TextChanged
	        ~~ txtPRCO06_TextChanged
	        ~~ chkPRCO07_CheckedChanged
	        ~~ chkPRCO08_CheckedChanged
	        ~~ chkPRCO09_CheckedChanged
	        ~~ chkPRCO10_CheckedChanged
	        ~~ chkPRRB01_CheckedChanged
	        ~~ chkPRRB02_CheckedChanged
	        +ProducaoSistema(IConfiguracaoSistema)
	        -Chk_CheckedChanged(object, EventArgs) void
	        +DesmarcarTodos() void
	        +Atualizar() void
	        -txtPRCO01_TextChanged(object, EventArgs) void
	        -txtPRCO02_Leave(object, EventArgs) void
	        -txtPRCO03_TextChanged(object, EventArgs) void
	        -cmbPRCO04_SelectedIndexChanged(object, EventArgs) void
	        -txtPRCO05_TextChanged(object, EventArgs) void
	        -txtPRCO06_TextChanged(object, EventArgs) void
	        -chkPRCO07_CheckedChanged(object, EventArgs) void
	        -chkPRCO08_CheckedChanged(object, EventArgs) void
	        -chkPRCO09_CheckedChanged(object, EventArgs) void
	        -chkPRCO10_CheckedChanged(object, EventArgs) void
	        -chkPRRB01_CheckedChanged(object, EventArgs) void
	        -chkPRRB02_CheckedChanged(object, EventArgs) void
	        -label12_Click(object, EventArgs) void
	        -panel1_Paint(object, PaintEventArgs) void
	        -label14_Click(object, EventArgs) void
	        -label5_Click(object, EventArgs) void
        }
        class LogisticaSistema {
	        -configuracao : IConfiguracaoSistema
	        ~~ chkLIRB01_CheckedChanged
	        ~~ chkLIRB02_CheckedChanged
	        ~~ chkLIRB03_CheckedChanged
	        ~~ chkLIRB04_CheckedChanged
	        ~~ chkLIRB05_CheckedChanged
	        ~~ chkLICO01_CheckedChanged
	        ~~ chkLICO02_CheckedChanged
	        ~~ chkLICO03_CheckedChanged
	        ~~ chkLICO04_CheckedChanged
	        ~~ chkLICO05_CheckedChanged
	        ~~ chkLICO06_CheckedChanged
	        ~~ chkLICO07_CheckedChanged
	        ~~ chkLICO08_CheckedChanged
	        ~~ chkLICO09_CheckedChanged
	        ~~ chkLIEE01_CheckedChanged
	        ~~ chkLIEE03_CheckedChanged
	        ~~ chkLIEE04_CheckedChanged
	        ~~ chkLICO15_CheckedChanged
	        ~~ txtLICO10_TextChanged
	        ~~ txtLICO11_Futura_TextChanged
	        ~~ txtLICO11_Passada_TextChanged
	        ~~ txtLICO12_TextChanged
	        ~~ cmbLICO13_SelectedIndexChanged
	        ~~ txtLICO14_TextChanged
	        ~~ txtLIEE02_TextChanged
	        ~~ txtLIEE05_TextChanged
	        ~~ txtLIEE06_TextChanged
	        ~~ txtLIEE07_TextChanged
	        ~~ btnConfigurarRoteirizacaoJSON_Click
	        +LogisticaSistema(IConfiguracaoSistema)
	        -Chk_CheckedChanged(object, EventArgs) void
	        +DesmarcarTodos() void
	        +Atualizar() void
	        -txtLICO10_TextChanged(object, EventArgs) void
	        -txtLICO10_Leave(object, EventArgs) void
	        -txtLICO11_Futura_TextChanged(object, EventArgs) void
	        -txtLICO11_Futura_Leave(object, EventArgs) void
	        -txtLICO11_Passada_TextChanged(object, EventArgs) void
	        -txtLICO11_Passada_Leave(object, EventArgs) void
	        -txtLICO12_TextChanged(object, EventArgs) void
	        -txtLICO12_Leave(object, EventArgs) void
	        -cmbLICO13_SelectedIndexChanged(object, EventArgs) void
	        -txtLICO14_TextChanged(object, EventArgs) void
	        -txtLIEE02_TextChanged(object, EventArgs) void
	        -txtLIEE05_TextChanged(object, EventArgs) void
	        -txtLIEE06_TextChanged(object, EventArgs) void
	        -txtLIEE07_TextChanged(object, EventArgs) void
	        -btnConfigurarRoteirizacaoJSON_Click(object, EventArgs) void
        }
	}
    
	<<updated>> IConfiguracaoSistema
	<<updated>> BarSistema
	<<updated>> ComercialSistema
	<<updated>> ComercialSistema1
	<<updated>> ProducaoSistema
	<<updated>> LogisticaSistema

    IConfiguracaoSistema <|-- Form
    IConfiguracaoSistema ..|> INotifyPropertyChanged
    IConfiguracaoSistema --> UserControl : currentControl "0..1"
    BarSistema --> IConfiguracaoSistema : configuracao "1"
    ComercialSistema --> IConfiguracaoSistema : configuracao "1"
    ComercialSistema1 --> IConfiguracaoSistema : configuracao "1"
    ProducaoSistema --> IConfiguracaoSistema : configuracao "1"
    LogisticaSistema --> IConfiguracaoSistema : configuracao "1"
   
    IConfiguracaoSistema ..> BarSistema : uses
    IConfiguracaoSistema ..> ComercialSistema : uses
    IConfiguracaoSistema ..> ComercialSistema1 : uses
    IConfiguracaoSistema ..> ProducaoSistema : uses
    IConfiguracaoSistema ..> LogisticaSistema : uses
