name: Regenerate Mermaid Diagrams

on:
  push:
    paths:
      - 'diagrams/**/*.mmd'

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow committing changes back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate PNGs from Mermaid files
        run: |
          mkdir -p diagrams
          for file in diagrams/*.mmd; do
            png="${file%.mmd}.png"
            mmdc -i "$file" -o "$png"
          done

      - name: Setup Python (for index script)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install YAML library
        run: pip install pyyaml

      - name: Update diagram index YAML
        run: python scripts/update_index.py

      - name: Commit updated diagrams and index
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update Mermaid diagram images and index"
          file_pattern: 'diagrams/* index.yml'
